### ISSUE TITLE
Let's implement GitHub login

### ISSUE THREAD

**Issue by n-d-r-d-g** [frontendmu/frontend.mu#163]
I tried logging in to Google but couldn't because it wasn't able to send me an OTP on my phone.
Due to Google's failure to authenticate me, I'm also not able to login on frontend.mu.

@MrSunshyne Let's implement it. I tried something but couldn't do much. I guess the endpoint needs to be created for it first.

**Comment by MrSunshyne** [comment]
This requires enabling the Auth Provider in directus. Maybe we can do it together on discord or on cedric's stream?

**Comment by n-d-r-d-g** [comment]
> This requires enabling the Auth Provider in directus. Maybe we can do it together on discord or on cedric's stream?

@MrSunshyne Apologies for the super late reply. I totally missed the notification. I noticed you already started the implementation. If you still need help, let's chat about it on Discord then decide how we'll proceed.

**Comment by MrSunshyne** [comment]
Yes we spent a few hours on this last week but didn't manage to get it fully working. We will give it another crack right after the meetup. I don't want risk breaking the site rsvp before the event 😬

Will ping you on discord when we plan the next session

**Comment by n-d-r-d-g** [comment]
> Yes we spent a few hours on this last week but didn't manage to get it fully working. We will give it another crack right after the meetup. I don't want risk breaking the site rsvp before the event 😬
> 
> Will ping you on discord when we plan the next session

Yeah good idea!
