### ISSUE TITLE
Move Social Media links to Nav Menu

### ISSUE THREAD

**Issue by derecklhw** [frontendmu/frontend.mu#195]

**Comment by the-code-raider** [comment]
Hello

I've recently came across a [website](https://chandrikadeb7.github.io/) that has the social media links which have a fixed positioning to the side of the page. We can maybe implement it on desktop as a way to quickly access the links.

[Screencast from 08-09-24 21:12:02.webm](https://github.com/user-attachments/assets/676141d1-49cd-4f96-b7e4-501fc03cbd06)
