### ISSUE TITLE
RSVP dock is not visible on the meetup page

### ISSUE THREAD

**Issue by the-code-raider** [frontendmu/frontend.mu#253]
I visited the [meetup page](https://frontend.mu/meetup/60) and can not see the rsvp option. Is that because rsvp is closed now ?

![Image](https://github.com/user-attachments/assets/1a24b763-2af9-41e8-9c0f-33d51da57f5c)

Update:
- I realized the rsvp close date is set to `today` after a quick investigation. This explains why it's not visible.

@MrSunshyne Can you please look into it when you've some time? 🙏

**Comment by MrSunshyne** [comment]
Thanks for the feedback!

You're correct. Since the initial date of the meetup was supposed to be tomorrow, rsvp closes today. I'm updating it. Thank you
